#!/usr/bin/env node

/**
 * Generates version.ts with a build-time date-based version number.
 * This script should be run before TypeScript compilation.
 */

const fs = require('fs');
const path = require('path');

// Generate YYYYMMDD format from current date
const today = new Date();
const year = today.getFullYear();
const month = String(today.getMonth() + 1).padStart(2, '0');
const day = String(today.getDate()).padStart(2, '0');
const versionNumber = parseInt(`${year}${month}${day}`, 10);

const versionTsContent = `/**
 * This file is auto-generated by scripts/generate-version.js
 * Do not edit manually. The version number is generated at build time
 * based on the release date in YYYYMMDD format.
 */

/**
 * Build-time version number in YYYYMMDD format for use with setSDKType.
 * This represents the date when the package was built/released.
 */
export const BUILD_VERSION = ${versionNumber};

/**
 * Returns the build-time version number.
 * This format is consistent with how other Bugfender SDKs handle version numbers.
 * 
 * @returns A number representing the build date in YYYYMMDD format (e.g., 20260116)
 */
export function getVersionNumber(): number {
  return BUILD_VERSION;
}
`;

const versionTsPath = path.join(__dirname, '../src/version.ts');
fs.writeFileSync(versionTsPath, versionTsContent, 'utf8');

console.log(`Generated version.ts with build version: ${versionNumber}`);
