/**
 * This file is auto-generated by scripts/generate-version.js
 * Do not edit manually. The version number is generated at build time
 * based on the release date in YYYYMMDD format.
 */

/**
 * Build-time version number in YYYYMMDD format for use with setSDKType.
 * This represents the date when the package was built/released.
 */
export const BUILD_VERSION = 20260116;

/**
 * Returns the build-time version number.
 * This format is consistent with how other Bugfender SDKs handle version numbers.
 * 
 * @returns A number representing the build date in YYYYMMDD format (e.g., 20260116)
 */
export function getVersionNumber(): number {
  return BUILD_VERSION;
}
